// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restoran.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	restoran.proto

It has these top-level messages:
	AddJadwalShiftReq
	UpdateJadwalShiftReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddJadwalShiftReq struct {
	ShiftCode    string `protobuf:"bytes,1,opt,name=ShiftCode" json:"ShiftCode,omitempty"`
	JadwalMasuk  string `protobuf:"bytes,2,opt,name=JadwalMasuk" json:"JadwalMasuk,omitempty"`
	JadwalPulang string `protobuf:"bytes,3,opt,name=JadwalPulang" json:"JadwalPulang,omitempty"`
	Status       int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreatedBy    string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn    string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy    string `protobuf:"bytes,7,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdatedOn    string `protobuf:"bytes,8,opt,name=UpdatedOn" json:"UpdatedOn,omitempty"`
}

func (m *AddJadwalShiftReq) Reset()                    { *m = AddJadwalShiftReq{} }
func (m *AddJadwalShiftReq) String() string            { return proto.CompactTextString(m) }
func (*AddJadwalShiftReq) ProtoMessage()               {}
func (*AddJadwalShiftReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddJadwalShiftReq) GetShiftCode() string {
	if m != nil {
		return m.ShiftCode
	}
	return ""
}

func (m *AddJadwalShiftReq) GetJadwalMasuk() string {
	if m != nil {
		return m.JadwalMasuk
	}
	return ""
}

func (m *AddJadwalShiftReq) GetJadwalPulang() string {
	if m != nil {
		return m.JadwalPulang
	}
	return ""
}

func (m *AddJadwalShiftReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddJadwalShiftReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddJadwalShiftReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *AddJadwalShiftReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *AddJadwalShiftReq) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

type UpdateJadwalShiftReq struct {
	ShiftCode    string `protobuf:"bytes,1,opt,name=ShiftCode" json:"ShiftCode,omitempty"`
	JadwalMasuk  string `protobuf:"bytes,2,opt,name=JadwalMasuk" json:"JadwalMasuk,omitempty"`
	JadwalPulang string `protobuf:"bytes,3,opt,name=JadwalPulang" json:"JadwalPulang,omitempty"`
	Status       int32  `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	CreatedBy    string `protobuf:"bytes,5,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn    string `protobuf:"bytes,6,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy    string `protobuf:"bytes,7,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdatedOn    string `protobuf:"bytes,8,opt,name=UpdatedOn" json:"UpdatedOn,omitempty"`
}

func (m *UpdateJadwalShiftReq) Reset()                    { *m = UpdateJadwalShiftReq{} }
func (m *UpdateJadwalShiftReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateJadwalShiftReq) ProtoMessage()               {}
func (*UpdateJadwalShiftReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateJadwalShiftReq) GetShiftCode() string {
	if m != nil {
		return m.ShiftCode
	}
	return ""
}

func (m *UpdateJadwalShiftReq) GetJadwalMasuk() string {
	if m != nil {
		return m.JadwalMasuk
	}
	return ""
}

func (m *UpdateJadwalShiftReq) GetJadwalPulang() string {
	if m != nil {
		return m.JadwalPulang
	}
	return ""
}

func (m *UpdateJadwalShiftReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateJadwalShiftReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *UpdateJadwalShiftReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *UpdateJadwalShiftReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *UpdateJadwalShiftReq) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func init() {
	proto.RegisterType((*AddJadwalShiftReq)(nil), "grpc.AddJadwalShiftReq")
	proto.RegisterType((*UpdateJadwalShiftReq)(nil), "grpc.UpdateJadwalShiftReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for JadwalShiftService service

type JadwalShiftServiceClient interface {
	AddJadwalShift(ctx context.Context, in *AddJadwalShiftReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	UpdateJadwalShift(ctx context.Context, in *UpdateJadwalShiftReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type jadwalShiftServiceClient struct {
	cc *grpc1.ClientConn
}

func NewJadwalShiftServiceClient(cc *grpc1.ClientConn) JadwalShiftServiceClient {
	return &jadwalShiftServiceClient{cc}
}

func (c *jadwalShiftServiceClient) AddJadwalShift(ctx context.Context, in *AddJadwalShiftReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.JadwalShiftService/AddJadwalShift", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jadwalShiftServiceClient) UpdateJadwalShift(ctx context.Context, in *UpdateJadwalShiftReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.JadwalShiftService/UpdateJadwalShift", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for JadwalShiftService service

type JadwalShiftServiceServer interface {
	AddJadwalShift(context.Context, *AddJadwalShiftReq) (*google_protobuf.Empty, error)
	UpdateJadwalShift(context.Context, *UpdateJadwalShiftReq) (*google_protobuf.Empty, error)
}

func RegisterJadwalShiftServiceServer(s *grpc1.Server, srv JadwalShiftServiceServer) {
	s.RegisterService(&_JadwalShiftService_serviceDesc, srv)
}

func _JadwalShiftService_AddJadwalShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJadwalShiftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JadwalShiftServiceServer).AddJadwalShift(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JadwalShiftService/AddJadwalShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JadwalShiftServiceServer).AddJadwalShift(ctx, req.(*AddJadwalShiftReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JadwalShiftService_UpdateJadwalShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJadwalShiftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JadwalShiftServiceServer).UpdateJadwalShift(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.JadwalShiftService/UpdateJadwalShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JadwalShiftServiceServer).UpdateJadwalShift(ctx, req.(*UpdateJadwalShiftReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _JadwalShiftService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.JadwalShiftService",
	HandlerType: (*JadwalShiftServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddJadwalShift",
			Handler:    _JadwalShiftService_AddJadwalShift_Handler,
		},
		{
			MethodName: "UpdateJadwalShift",
			Handler:    _JadwalShiftService_UpdateJadwalShift_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "restoran.proto",
}

func init() { proto.RegisterFile("restoran.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc9, 0x2f, 0x4a, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48,
	0x96, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0xa7,
	0xe6, 0x16, 0x94, 0x54, 0x42, 0x94, 0x28, 0xb5, 0x33, 0x71, 0x09, 0x3a, 0xa6, 0xa4, 0x78, 0x25,
	0xa6, 0x94, 0x27, 0xe6, 0x04, 0x67, 0x64, 0xa6, 0x95, 0x04, 0xa5, 0x16, 0x0a, 0xc9, 0x70, 0x71,
	0x82, 0xd9, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x21,
	0x05, 0x2e, 0x6e, 0x88, 0x7a, 0xdf, 0xc4, 0xe2, 0xd2, 0x6c, 0x09, 0x26, 0xb0, 0x3c, 0xb2, 0x90,
	0x90, 0x12, 0x17, 0x0f, 0x84, 0x1b, 0x50, 0x9a, 0x93, 0x98, 0x97, 0x2e, 0xc1, 0x0c, 0x56, 0x82,
	0x22, 0x26, 0x24, 0xc6, 0xc5, 0x16, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x2c, 0xc1, 0xa2, 0xc0, 0xa8,
	0xc1, 0x1a, 0x04, 0xe5, 0x81, 0xec, 0x76, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x4d, 0x71, 0xaa, 0x94,
	0x60, 0x85, 0xd8, 0x0d, 0x17, 0x40, 0x92, 0xf5, 0xcf, 0x93, 0x60, 0x43, 0x91, 0xf5, 0xcf, 0x03,
	0xc9, 0x86, 0x16, 0xa4, 0x40, 0xf5, 0xb2, 0x43, 0x64, 0xe1, 0x02, 0x48, 0xb2, 0xfe, 0x79, 0x12,
	0x1c, 0x28, 0xb2, 0xfe, 0x79, 0x4a, 0x5d, 0x4c, 0x5c, 0x22, 0x10, 0xde, 0x68, 0x60, 0x18, 0x2d,
	0x61, 0xe4, 0x12, 0x42, 0x0a, 0x86, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x67, 0x2e,
	0x3e, 0xd4, 0xc4, 0x22, 0x24, 0xae, 0x07, 0x4a, 0x63, 0x7a, 0x18, 0x49, 0x48, 0x4a, 0x4c, 0x0f,
	0x92, 0xec, 0xf4, 0x60, 0xc9, 0x4e, 0xcf, 0x15, 0x94, 0xec, 0x94, 0x18, 0x84, 0x3c, 0xb9, 0x04,
	0x31, 0xc2, 0x59, 0x48, 0x0a, 0x62, 0x0e, 0xb6, 0x08, 0xc0, 0x6d, 0x54, 0x12, 0x1b, 0x58, 0xc4,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x70, 0x60, 0x70, 0xf9, 0x02, 0x00, 0x00,
}
