// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	AddUserReq
	UpdateUserReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 4.
type AddUserReq struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Pwd       string `protobuf:"bytes,3,opt,name=pwd" json:"pwd,omitempty"`
	Idkyw     string `protobuf:"bytes,4,opt,name=idkyw" json:"idkyw,omitempty"`
	Status    int32  `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	CreatedBy string `protobuf:"bytes,6,opt,name=createdBy" json:"createdBy,omitempty"`
	CreatedOn string `protobuf:"bytes,7,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdatedBy string `protobuf:"bytes,8,opt,name=updatedBy" json:"updatedBy,omitempty"`
	UpdatedOn string `protobuf:"bytes,9,opt,name=updatedOn" json:"updatedOn,omitempty"`
}

func (m *AddUserReq) Reset()                    { *m = AddUserReq{} }
func (m *AddUserReq) String() string            { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()               {}
func (*AddUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddUserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AddUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *AddUserReq) GetIdkyw() string {
	if m != nil {
		return m.Idkyw
	}
	return ""
}

func (m *AddUserReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddUserReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddUserReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *AddUserReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *AddUserReq) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

type UpdateUserReq struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Pwd       string `protobuf:"bytes,3,opt,name=pwd" json:"pwd,omitempty"`
	Idkyw     string `protobuf:"bytes,4,opt,name=idkyw" json:"idkyw,omitempty"`
	Status    int32  `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
	CreatedBy string `protobuf:"bytes,6,opt,name=createdBy" json:"createdBy,omitempty"`
	CreatedOn string `protobuf:"bytes,7,opt,name=createdOn" json:"createdOn,omitempty"`
	UpdatedBy string `protobuf:"bytes,8,opt,name=updatedBy" json:"updatedBy,omitempty"`
	UpdatedOn string `protobuf:"bytes,9,opt,name=updatedOn" json:"updatedOn,omitempty"`
}

func (m *UpdateUserReq) Reset()                    { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()               {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateUserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *UpdateUserReq) GetIdkyw() string {
	if m != nil {
		return m.Idkyw
	}
	return ""
}

func (m *UpdateUserReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateUserReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *UpdateUserReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *UpdateUserReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *UpdateUserReq) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserReq)(nil), "grpc.AddUserReq")
	proto.RegisterType((*UpdateUserReq)(nil), "grpc.UpdateUserReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	AddUser(ctx context.Context, in *AddUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
}

type userServiceClient struct {
	cc *grpc1.ClientConn
}

func NewUserServiceClient(cc *grpc1.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.UserService/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.UserService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	AddUser(context.Context, *AddUserReq) (*google_protobuf.Empty, error)
	UpdateUser(context.Context, *UpdateUserReq) (*google_protobuf.Empty, error)
}

func RegisterUserServiceServer(s *grpc1.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0xb6, 0x49, 0x9b, 0x11, 0xa5, 0x8c, 0x52, 0x96, 0xe8, 0xa1, 0xe4, 0xd4, 0xd3,
	0x16, 0x14, 0x4f, 0x9e, 0x14, 0x3c, 0x07, 0x22, 0x7d, 0x80, 0x34, 0x3b, 0x86, 0xa0, 0x4d, 0xe2,
	0x26, 0xb1, 0xe4, 0xe8, 0x1b, 0x0b, 0xbe, 0x80, 0xec, 0x6e, 0x6c, 0x9a, 0x83, 0x4f, 0xe0, 0x6d,
	0xff, 0xef, 0xdf, 0x7f, 0x61, 0x66, 0x7f, 0x80, 0xa6, 0x22, 0x25, 0x4a, 0x55, 0xd4, 0x05, 0x4e,
	0x52, 0x55, 0x26, 0xfe, 0x55, 0x5a, 0x14, 0xe9, 0x1b, 0xad, 0x0d, 0xdb, 0x36, 0x2f, 0x6b, 0xda,
	0x95, 0x75, 0x6b, 0xaf, 0x04, 0x5f, 0x0c, 0xe0, 0x41, 0xca, 0x4d, 0x45, 0x2a, 0xa2, 0x77, 0x3c,
	0x87, 0x51, 0x26, 0x39, 0x5b, 0xb2, 0x95, 0x17, 0x8d, 0x32, 0x89, 0x3e, 0xcc, 0xf4, 0x7b, 0x79,
	0xbc, 0x23, 0x3e, 0x32, 0xf4, 0xa0, 0x71, 0x0e, 0xe3, 0x72, 0x2f, 0xf9, 0xd8, 0x60, 0x7d, 0xc4,
	0x4b, 0x70, 0x32, 0xf9, 0xda, 0xee, 0xf9, 0xc4, 0x30, 0x2b, 0x70, 0x01, 0x6e, 0x55, 0xc7, 0x75,
	0x53, 0x71, 0x67, 0xc9, 0x56, 0x4e, 0xd4, 0x29, 0xbc, 0x06, 0x2f, 0x51, 0x14, 0xd7, 0x24, 0x1f,
	0x5b, 0xee, 0x9a, 0x44, 0x0f, 0x8e, 0xdc, 0x30, 0xe7, 0xd3, 0x81, 0x1b, 0xe6, 0xda, 0x6d, 0x4a,
	0xd9, 0x65, 0x67, 0xd6, 0x3d, 0x80, 0x23, 0x37, 0xcc, 0xb9, 0x37, 0x70, 0xc3, 0x3c, 0xf8, 0x66,
	0x70, 0xb6, 0x31, 0xea, 0x1f, 0x4d, 0x7d, 0xf3, 0xc9, 0xe0, 0x54, 0xcf, 0xfb, 0x4c, 0xea, 0x23,
	0x4b, 0x08, 0xef, 0x60, 0xda, 0xfd, 0x3b, 0xce, 0x85, 0xee, 0x89, 0xe8, 0x6b, 0xe0, 0x2f, 0x84,
	0xed, 0x8c, 0xf8, 0xed, 0x8c, 0x78, 0xd2, 0x9d, 0x09, 0x4e, 0xf0, 0x1e, 0xa0, 0xdf, 0x1d, 0x5e,
	0xd8, 0xe4, 0x60, 0x9b, 0x7f, 0x87, 0xb7, 0xae, 0x21, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x4c, 0xd0, 0x64, 0x28, 0xa4, 0x02, 0x00, 0x00,
}
